name: aws-v5
on:
  push:
    branches:
      - main

# https://github.com/actions/setup-java
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build: # build는 작업이름(내가 원하는 이름으로 수정가능)
    runs-on: ubuntu-latest
    steps: # step의 name들은 그냥 이름 내가 value 지정
      - name: Checkout   # 코드 다운로드
        uses: actions/checkout@v3
      - name: Set up JDK 11    # jdk 설치
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Pemission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
